version: '3.8'

services:
  recursos:
    image: msvc-recursos
    ports:
      - "8081:8080"

  proyecto:
    image: msvc-proyecto
    ports:
      - "8082:8080"

  colaboracion:
    image: msvc-colaboracion
    ports:
      - "8083:8080"

  autentificacion:
    image: msvc-autentificacion
    ports:
    - "8080:8080"