version: '3.8'

services:
  msvc-proyecto:
    image: ${ECR_REGISTRY}/msvc-proyecto:latest
    ports:
      - "8081:8080"
    deploy:
      restart_policy:
        condition: on-failure

  msvc-autentificacion:
    image: ${ECR_REGISTRY}/msvc-autentificacion:latest
    ports:
      - "8082:8080"
    deploy:
      restart_policy:
        condition: on-failure

  msvc-colaboracion:
    image: ${ECR_REGISTRY}/msvc-colaboracion:latest
    ports:
      - "8083:8080"
    deploy:
      restart_policy:
        condition: on-failure

  msvc-recursos:
    image: ${ECR_REGISTRY}/msvc-recursos:latest
    ports:
      - "8084:8080"
    deploy:
      restart_policy:
        condition: on-failure
