spring.application.name=msvc-recursos
server.port=8002

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

spring.datasource.url=jdbc:h2:file:./data/msvc_recursos
spring.datasource.username=${DB_USERNAME:usuario}
spring.datasource.password=${DB_PASSWORD:clave}

spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console